version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/"
    target-branch: "main"
    groups:
      pip-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
    schedule:
      interval: "daily"
    labels:
      - "patch"
      - "dependencies"
    open-pull-requests-limit: 0

  - package-ecosystem: "maven"
    directories:
      - "/"
      - "/ssdc-rm-common-entity-model"
    target-branch: "main"
    groups:
      maven-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
    schedule:
      interval: "daily"
    labels:
      - "patch"
      - "dependencies"
    open-pull-requests-limit: 0

# Update GitHub actions in workflows
  - package-ecosystem: github-actions
    directory: /
    # Every week
    schedule:
      interval: weekly

    labels:
      - "patch"
      - "dependencies"

    groups:
      # Group updates into fewer pull requests
      gh-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
    open-pull-requests-limit: 0