sudo: required

services:
  - docker

jobs:
  include:
    - language: python

      python:
        - "3.9"

      install:
        - pip uninstall -y numpy  # Remove the vulnerable Numpy which Travis provides
        - pip install -U pipenv
        - pipenv install --dev --deploy

      script:
        - pipenv check
        - pipenv run flake8
        - pipenv run pytest test --cov=. --cov-report term-missing

      after_success:
        - pipenv run codecov

      env:
        global:
          - PIPENV_IGNORE_VIRTUALENVS=1

    - language: java
      jdk: openjdk17

      before_install:
        - make format-check-common
        - echo "$GOOGLE_SERVICE_ACCOUNT_KEY" > ~/google-service-account-key.json
        - export GOOGLE_APPLICATION_CREDENTIALS=~/google-service-account-key.json

      install: echo "SKIPPING DEFAULT INSTALL" # Travis has a default maven install. Don't build twice!

      script: travis_wait make build-common

      cache:
        directories:
          - $HOME/.m2
branches:
  only:
    - main
