sudo: required

services:
  - docker

jobs:
  include:
    - language: python
      python:
        - "3.10.8"
      dist: bionic # The default dist does not yet support python 3.10
      name: "Python Tests and Checks"

      before_install:
        - deactivate # Deactivate the virtualenv Travis dumps us in, so that we can fix out of date global dependencies
        - pyenv global 3.10 # Ensure the right global python version is being used
        - pip install --upgrade pip pipenv setuptools wheel

      install:
        - pipenv install --dev --deploy

      script:
        - pipenv check -i 51499 -i 51457
        - pipenv run flake8
        - pipenv run pytest test --cov=. --cov-report term-missing

      after_success:
        - pipenv run codecov

      env:
        global:
          - PIPENV_IGNORE_VIRTUALENVS=1

    - language: python
      python:
        - "3.10.8"
      dist: bionic # The default dist does not yet support python 3.10
      sudo: required
      name: "Test Patches"
      services:
        - docker
      before_install:
        - docker login -u "${DOCKER_GCP_USERNAME}" -p "${GOOGLE_SERVICE_ACCOUNT_KEY}" https://europe-west2-docker.pkg.dev;
        - docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}";
        - deactivate # Deactivate the virtualenv Travis dumps us in, so that we can fix out of date global dependencies
        - pyenv global 3.10 # Ensure the right global python version is being used
        - pip install --upgrade pip pipenv setuptools wheel

      install:
        - pipenv install --dev --deploy

      script:
        - make test-patches

    - language: java
      jdk: openjdk17
      name: "Java Common Entities"
      before_install:
        - echo "$GOOGLE_SERVICE_ACCOUNT_KEY" > ~/google-service-account-key.json
        - export GOOGLE_APPLICATION_CREDENTIALS=~/google-service-account-key.json
        - make format-check-common

      install: echo "SKIPPING DEFAULT INSTALL" # Travis has a default maven install. Don't build twice!

      script: travis_wait make build-common

      cache:
        directories:
          - $HOME/.m2

    - language: bash
      name: "Shell Check"
      script:
        - make shellcheck

branches:
  only:
    - main
