services:
  dev-postgres:
    container_name: dev-postgres-ddl
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-dev-common-postgres:latest
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=500" ]
    ports:
      - "16432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5