from enum import Enum


class EventType(Enum):
    NEW_CASE = 1
    RECEIPT = 2
    REFUSAL = 3
    ERASE_DATA = 4
    EQ_LAUNCH = 5
    INVALID_CASE = 6
    UAC_AUTHENTICATION = 7
    TELEPHONE_CAPTURE = 8
    PRINT_FULFILMENT = 9
    EXPORT_FILE = 10
    DEACTIVATE_UAC = 11
    UPDATE_SAMPLE = 12
    UPDATE_SAMPLE_SENSITIVE = 13
    SMS_FULFILMENT = 14
    ACTION_RULE_SMS_REQUEST = 14
    EMAIL_FULFILMENT = 14
    ACTION_RULE_EMAIL_REQUEST = 16
    ACTION_RULE_SMS_CONFIRMATION = 17
    ACTION_RULE_EMAIL_CONFIRMATION = 18
