package uk.gov.ons.ssdc.common.model.entity;

public enum EventType {
  NEW_CASE,
  RECEIPT,
  REFUSAL,
  EQ_LAUNCH,
  INVALID_CASE,
  UAC_AUTHENTICATION,
  TELEPHONE_CAPTURE,
  EXPORT_FILE_FULFILMENT,
  EXPORT_FILE,
  DEACTIVATE_UAC,
  UPDATE_SAMPLE_SENSITIVE,
  SMS_FULFILMENT,
  ACTION_RULE_SMS_REQUEST
}
