name: Checks and Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  python-tests:
    name: Python Checks and Tests
    runs-on: ubuntu-latest

    # Add "id-token" with the required permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate with Google to acquire a token for authenticating with the docker registry
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      # Authenticating with Dockerhub ensures image pulls are authenticated, so not as severely rate limited
      - name: Log in to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Also log docker in to GCP artifact registry, to allow image pulls from our private registries
      - name: Log in to Google Docker Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Python "3.11"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip pipenv==2024.0.1
          pipenv install --dev --deploy

      - name: Run Tests and Checks
        run: make test

      - name: Check Docker Build
        run: make build-ddl-docker

  patches-tests:
    name: Test DDL Patches
    runs-on: ubuntu-latest

    # Add "id-token" with the required permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate with Google to acquire a token for authenticating with the docker registry
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      # Authenticating with Dockerhub ensures image pulls are authenticated, so not as severely rate limited
      - name: Log in to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Also log docker in to GCP artifact registry, to allow image pulls from our private registries
      - name: Log in to Google Docker Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Python "3.11"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev --deploy

      - name: Run Tests and Checks
        run: make test-patches

  dev-postgres-tests:
    name: Test Dev Postgres
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests and Checks
        run: make test-dev-postgres

  ddl-java-checks:
    name: DDL Java Checks
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Maven Checks
        run: make check-ddl


  common-entities-java-checks:
    name: Common Entities Java Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ssdc-rm-common-entity-model

    # Add "id-token" with the required permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Checkout
        uses: actions/checkout@v4
          
      # Authenticate with Google to acquire a token for authenticating with the docker registry
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Maven Checks
        run: make format-check

      - name: Run Build
        run: make build


  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Shellcheck
        run: make shellcheck
